# Generated by Django 5.1.3 on 2024-11-16 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_commentmodel_commentlikemodel_postlikemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.commentmodel'),
        ),
    ]
